### ISSUE TITLE
Ignore Key Inputs?

### ISSUE THREAD

**Issue by TheIzzyKirby** [polydes/dialog#3]
I need a player actor to stay still and not be able to move until the dialog is over. Also I need the "Start Dialog" and "Advance Dialog" buttons to have a short time where inputs are ignored to prevent accidently starting the dialog again, especially if both buttons are the same.

**Comment by justin-espedal** [comment]
To keep your actor from moving when dialog is active, you can check whether dialog is currently active or not in your behaviors and apply the appropriate logic changes. Here's a simple guide that shows how you might do that.

http://www.polydes.com/repo/toolset/com.polydes.dialog/guides/code_while_running_dialog/

To prevent dialog from being opened again right away, you'll need to set up a timer yourself. Here's an example.

![image](https://user-images.githubusercontent.com/826810/159131345-2598cbde-aee0-435e-bfec-cafb819b84fc.png)

**Comment by TheIzzyKirby** [comment]
Thank you. I was using "Do after () seconds" to delay input, but I feel like Stencyl was storing inputs during it.

**Comment by justin-espedal** [comment]
I see! This section of Luyen's video on the basic Stencyl events may help with the use of timers. https://youtu.be/j10SMwy2prM?t=172
